(function(){
  const storageKey=p=>`treinoTrincaWorkouts_${p}`;
  let editing=null;
  const searchAliases={agachamento:'squat',agachar:'squat',supino:'bench press',inclinado:'incline',remada:'row',stiff:'romanian deadlift',terra:'deadlift',romeno:'romanian deadlift',lateral:'lateral raise',rosca:'curl',biceps:'curl',bíceps:'curl',triceps:'tricep',tríceps:'tricep',panturrilha:'calf raise',abdominal:'crunch',abdomen:'crunch',leg:'leg',perna:'leg',peito:'chest',costas:'back',ombro:'shoulder',ombros:'shoulder',quadriceps:'quadriceps',quadríceps:'quadriceps,leg',posterior:'hamstring',gluteo:'glute',glúteo:'glute',gluteos:'glute',glúteos:'glute'};
  function loadSaved(){try{return JSON.parse(localStorage.getItem(storageKey(profile))||'{}')}catch{return{}}}
  function saveSaved(x){localStorage.setItem(storageKey(profile),JSON.stringify(x))}
  function clone(x){return JSON.parse(JSON.stringify(x))}
  function escLocal(v){return typeof esc==='function'?esc(v):String(v??'')}
  function isBase(k){return profiles[profile].codes.includes(k)}
  function applySaved(){const saved=loadSaved();Object.keys(saved).forEach(k=>{workouts[k]=saved[k]})}
  function allCodes(){const base=profiles[profile].codes.slice();Object.keys(workouts).forEach(k=>{if(!base.includes(k))base.push(k)});return base}

  function renderListV16(c){
    const p=profiles[profile],codes=allCodes();
    c.innerHTML=`<div class="card"><h2>Treinos ${p.emoji}</h2><div class="muted small">Perfil atual: ${escLocal(p.label)}</div><p class="muted small">Personalize exercícios, séries e repetições sem alterar o treino original.</p><button type="button" class="primary compact-btn" data-editor-action="new">➕ Criar treino</button></div><h3 class="section-title">Meus treinos</h3>${codes.map(k=>{const w=workouts[k];if(!w)return'';return `<div class="workout-list-row"><button type="button" class="listbtn ${k===current?'selected-workout':''}" data-editor-action="select" data-code="${escLocal(k)}"><b>Treino ${escLocal(k)}</b> — ${escLocal(w.name||'')} ${k===current?'· Atual':''}<br><span class="muted small">${w.items?.length||0} exercícios</span></button><button type="button" class="secondary edit-workout-btn" title="Editar" data-editor-action="edit" data-code="${escLocal(k)}">✏️</button><button type="button" class="secondary compact-btn" title="Duplicar" data-editor-action="duplicate" data-code="${escLocal(k)}">📋</button>${!isBase(k)?`<button type="button" class="secondary delete-workout-btn" title="Excluir" data-editor-action="delete" data-code="${escLocal(k)}">🗑️</button>`:''}</div>`}).join('')}`;
  }

  function newWorkoutV16(){const code=`${profile==='masculino'?'M':'E'}${Date.now().toString().slice(-6)}`;const w={id:code,name:'Novo treino',items:[]};workouts[code]=w;const saved=loadSaved();saved[code]=w;saveSaved(saved);editWorkoutV16(code)}
  function duplicateWorkoutV16(code){const src=workouts[code];if(!src)return;const id=`${profile==='masculino'?'M':'E'}${Date.now().toString().slice(-6)}`;const w=clone(src);w.id=id;w.name=`${src.name||'Treino'} (cópia)`;workouts[id]=w;const saved=loadSaved();saved[id]=w;saveSaved(saved);setCurrent(id);editWorkoutV16(id)}
  function deleteWorkoutV16(code){if(isBase(code)){alert('Os treinos padrão não podem ser excluídos.');return}if(!confirm(`Excluir o treino ${code}?`))return;delete workouts[code];const saved=loadSaved();delete saved[code];saveSaved(saved);if(current===code)setCurrent(profiles[profile].codes[0]);renderListV16(content)}

  function rowHtml(it,i,total){return `<div class="editor-exercise"><div class="editor-exercise-title"><strong>${i+1}. ${escLocal(it.name)}</strong><button type="button" class="secondary compact-btn" data-editor-action="swap" data-index="${i}">🔄 Trocar</button></div><div class="editor-grid"><label>Exercício<input id="ename_${i}" value="${escLocal(it.name)}" data-editor-field="name" data-index="${i}"></label><label>Séries<input type="number" min="1" max="20" id="esets_${i}" value="${Number(it.sets)||1}" data-editor-field="sets" data-index="${i}"></label><label>Repetições<input id="ereps_${i}" value="${escLocal(it.reps||'')}" data-editor-field="reps" data-index="${i}"></label></div><div class="editor-order">${i?`<button type="button" class="secondary" data-editor-action="move" data-index="${i}" data-delta="-1">↑</button>`:''}${i<total-1?`<button type="button" class="secondary" data-editor-action="move" data-index="${i}" data-delta="1">↓</button>`:''}<button type="button" class="secondary" data-editor-action="remove" data-index="${i}">🗑️ Remover</button></div><div id="swap_${i}" class="editor-result"></div></div>`}

  function editWorkoutV16(code){const w=workouts[code];if(!w)return;editing=clone(w);renderEditor()}
  function renderEditor(){if(!editing)return;const c=document.getElementById('content');c.innerHTML=`<div class="card"><h2>✏️ Editar Treino ${escLocal(editing.id)}</h2><label class="editor-name-label">Nome do treino<input id="editorWorkoutName" value="${escLocal(editing.name||'')}" data-editor-field="workout-name"></label><div class="muted small" style="margin-top:8px">Troque exercícios pelo RepDB, ajuste séries/repetições e altere a ordem.</div></div><div id="editorExercises">${editing.items.map((it,i)=>rowHtml(it,i,editing.items.length)).join('')||'<div class="empty">Nenhum exercício. Use "Adicionar exercício".</div>'}</div><div class="card editor-actions"><button type="button" class="primary" data-editor-action="add">➕ Adicionar exercício</button><button type="button" class="primary" data-editor-action="save">💾 Salvar treino</button><button type="button" class="secondary" style="width:100%;margin-top:8px" data-editor-action="cancel">Cancelar</button>${isBase(editing.id)?`<button type="button" class="secondary" style="width:100%;margin-top:8px" data-editor-action="reset" data-code="${escLocal(editing.id)}">↩️ Restaurar padrão</button>`:''}</div>`}

  function updateField(el){if(!editing)return;const i=Number(el.dataset.index),field=el.dataset.editorField;if(field==='workout-name'){editing.name=el.value;return}if(!editing.items[i])return;editing.items[i][field]=field==='sets'?Math.max(1,Number(el.value)||1):el.value}
  function moveExerciseV16(i,delta){if(!editing)return;const j=i+delta;if(j<0||j>=editing.items.length)return;[editing.items[i],editing.items[j]]=[editing.items[j],editing.items[i]];renderEditor()}
  function removeExerciseV16(i){if(!editing)return;editing.items.splice(i,1);renderEditor()}
  function addExerciseV16(){if(!editing)return;editing.items.push({name:'Agachamento',sets:3,reps:'8–12'});renderEditor();openSwapV16(editing.items.length-1)}

  function openSwapV16(i){const box=document.getElementById(`swap_${i}`);if(!box||!editing?.items[i])return;box.innerHTML=`<input class="editor-search" placeholder="🔍 Buscar exercício (português ou inglês)" data-swap-search="${i}"><div class="muted small" style="margin-top:6px">Sugestões:</div><div id="swapResults_${i}"></div>`;searchSwapV16(i,'');box.querySelector('[data-swap-search]')?.focus()}
  function normalizeSearch(q){const raw=String(q||'').trim().toLowerCase();if(!raw)return'';const parts=raw.normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/\s+/).map(x=>searchAliases[x]||x);return parts.join(' ')}
  function repdbResults(query,currentName){
    if(!window.RepDB||!RepDB.loaded)return[];
    const q=normalizeSearch(query);
    if(q){let result=RepDB.search(q);if(!result.length){const words=q.split(/\s+/).filter(Boolean);result=RepDB.search('').filter(ex=>{const hay=[ex.id,ex.name_en,ex.name_de,ex.name_es,ex.description_en,ex.equipment,ex.body_part,...(ex.primary_muscles||[]),...(ex.secondary_muscles||[]),...(ex.tags||[]),...(ex.goals||[])].join(' ').toLowerCase();return words.every(w=>hay.includes(w))})}return result.slice(0,20)}
    const cur=RepDB.candidates(mediaMap[currentName]||[]),body=cur?.body_part,primary=cur?.primary_muscles||[];
    return RepDB.search('').filter(ex=>(!body||ex.body_part===body)&&(!primary.length||primary.some(m=>(ex.primary_muscles||[]).includes(m)))).slice(0,12)
  }
  function searchSwapV16(i,q){const box=document.getElementById(`swapResults_${i}`);if(!box)return;const list=repdbResults(q,editing?.items[i]?.name);box.innerHTML=list.slice(0,8).map((ex,n)=>`<button type="button" class="secondary swap-option" data-editor-action="choose" data-index="${i}" data-repdb-index="${n}" style="width:100%;text-align:left;margin-top:5px"><b>${escLocal(ex.name_en||ex.id)}</b><span class="muted small"> · ${escLocal(RepDB.label(ex.body_part)||'')}</span></button>`).join('')||'<div class="empty">Nenhum resultado. Aguarde o catálogo carregar ou tente outro termo.</div>';box._results=list.slice(0,8)}
  function chooseExerciseV16(i,n){if(!editing?.items[i])return;const box=document.getElementById(`swapResults_${i}`);const ex=box?._results?.[n];if(!ex)return;editing.items[i].name=ex.name_en||ex.id;mediaMap[editing.items[i].name]=[ex.id];renderEditor()}
  function saveWorkoutV16(){if(!editing)return;editing.items=editing.items.filter(x=>x&&String(x.name||'').trim()).map(x=>({name:String(x.name).trim(),sets:Math.max(1,Number(x.sets)||1),reps:String(x.reps||'').trim()||'8–12'}));workouts[editing.id]=clone(editing);const saved=loadSaved();saved[editing.id]=clone(editing);saveSaved(saved);setCurrent(editing.id);editing=null;show('treinos')}
  function resetWorkoutV16(code){if(!isBase(code))return;const saved=loadSaved();delete saved[code];saveSaved(saved);const defaults=window.__trincaDefaults?.[code];if(defaults)workouts[code]=clone(defaults);else{location.reload();return}editWorkoutV16(code)}

  document.addEventListener('click',function(ev){const btn=ev.target.closest('[data-editor-action]');if(!btn)return;const action=btn.dataset.editorAction,code=btn.dataset.code,i=Number(btn.dataset.index);ev.preventDefault();ev.stopPropagation();if(action==='new')newWorkoutV16();else if(action==='select'){setCurrent(code);show('hoje')}else if(action==='edit')editWorkoutV16(code);else if(action==='duplicate')duplicateWorkoutV16(code);else if(action==='delete')deleteWorkoutV16(code);else if(action==='swap')openSwapV16(i);else if(action==='move')moveExerciseV16(i,Number(btn.dataset.delta));else if(action==='remove')removeExerciseV16(i);else if(action==='add')addExerciseV16();else if(action==='save')saveWorkoutV16();else if(action==='cancel'){editing=null;show('treinos')}else if(action==='reset')resetWorkoutV16(code);else if(action==='choose')chooseExerciseV16(i,Number(btn.dataset.repdbIndex))},true);
  document.addEventListener('input',function(ev){const el=ev.target;if(el.matches('[data-editor-field]'))updateField(el);if(el.matches('[data-swap-search]'))searchSwapV16(Number(el.dataset.swapSearch),el.value)},true);

  function install(){if(!window.__trincaDefaults)window.__trincaDefaults={};Object.keys(workouts).forEach(k=>{if(isBase(k)&&!window.__trincaDefaults[k])window.__trincaDefaults[k]=clone(workouts[k])});applySaved();window.renderList=renderListV16;if(tab==='treinos')renderListV16(content)}
  window.newWorkoutV16=newWorkoutV16;window.duplicateWorkoutV16=duplicateWorkoutV16;window.deleteWorkoutV16=deleteWorkoutV16;window.editWorkoutV16=editWorkoutV16;window.moveExerciseV16=moveExerciseV16;window.removeExerciseV16=removeExerciseV16;window.addExerciseV16=addExerciseV16;window.swapExerciseV16=openSwapV16;window.searchSwapV16=searchSwapV16;window.chooseExerciseV16=chooseExerciseV16;window.saveWorkoutV16=saveWorkoutV16;window.resetWorkoutV16=resetWorkoutV16;
  const timer=setInterval(()=>{if(typeof workouts!=='undefined'&&Object.keys(workouts).length){clearInterval(timer);install()}},100);
})();
