const RepDBPTBR = (() => {
  const body = {back:'Costas',chest:'Peito',core:'Core / Abdômen',full_body:'Corpo inteiro',lower_arms:'Antebraços',lower_legs:'Panturrilhas',shoulders:'Ombros',upper_arms:'Braços',upper_legs:'Pernas'};
  const equipment = {ab_crunch_machine:'Máquina abdominal',ab_wheel:'Roda abdominal',air_bike:'Air bike',assisted_pullup_machine:'Máquina de barra fixa assistida',back_extension_machine:'Máquina de extensão lombar',barbell:'Barra',battle_rope:'Corda naval',bicep_curl_machine:'Máquina de bíceps',cable:'Polia',chest_fly_machine:'Máquina de peck deck',chest_press_machine:'Máquina de supino',climbing_rope:'Corda de escalada',dip_machine:'Máquina de mergulho assistido',dip_station:'Paralelas',dumbbell:'Halteres',ez_bar:'Barra W',elliptical:'Elíptico',flat_bench:'Banco reto',glute_ham_developer:'Banco GHD',rings:'Argolas',hack_squat:'Hack squat',hip_abduction_machine:'Máquina abdutora',hip_adduction_machine:'Máquina adutora',hip_thrust_machine:'Máquina de elevação pélvica',jump_rope:'Corda de pular',kettlebell:'Kettlebell',lat_pulldown_machine:'Máquina de puxada alta',leg_curl:'Mesa flexora',leg_extension:'Cadeira extensora',leg_press:'Leg press',loop_band:'Mini band',pec_deck:'Peck deck',plate_loaded_lateral_raise_machine:'Máquina de elevação lateral',plyo_box:'Caixa pliométrica',preacher_curl_machine:'Máquina Scott',pull_up_bar:'Barra fixa',resistance_band:'Faixa elástica',rower:'Remo ergométrico',seated_calf_raise_machine:'Máquina de panturrilha sentada',shoulder_press_machine:'Máquina de desenvolvimento',shrug_machine:'Máquina de encolhimento',slam_ball:'Slam ball',sled:'Trenó',smith_machine:'Smith',stability_ball:'Bola suíça',stair_climber:'Escada',standing_calf_raise_machine:'Máquina de panturrilha em pé',stationary_bike:'Bicicleta ergométrica',suspension_trainer:'Suspensão',trap_bar:'Barra hexagonal',treadmill:'Esteira',tricep_extension_machine:'Máquina de tríceps',plates:'Anilhas',wrist_roller:'Rolo de punho'};
  const muscles = {rectus_abdominis:'reto abdominal',transverse_abdominis:'transverso do abdômen',anterior_deltoid:'deltoide anterior',lateral_deltoid:'deltoide lateral',posterior_deltoid:'deltoide posterior',pectoralis_major:'peitoral maior',pectoralis_minor:'peitoral menor',latissimus_dorsi:'dorsal',biceps_brachii:'bíceps',triceps_brachii:'tríceps',brachialis:'braquial',forearm_flexors:'flexores do antebraço',forearm_extensors:'extensores do antebraço',trapezius:'trapézio',rhomboids:'romboides',serratus_anterior:'serrátil anterior',erector_spinae:'eretores da coluna',lower_back:'lombar',middle_back:'parte média das costas',gluteus_maximus:'glúteo máximo',gluteus_medius:'glúteo médio',hamstrings:'posteriores de coxa',quadriceps:'quadríceps',calves:'panturrilhas',gastrocnemius:'gastrocnêmio',soleus:'sóleo',obliques:'oblíquos',hip_flexors:'flexores do quadril',adductors:'adutores',abductors:'abdutores',forearms:'antebraços',neck:'pescoço'};
  const category = {strength:'Força',stretching:'Alongamento',cardio:'Cardio',plyometrics:'Pliometria',powerlifting:'Powerlifting',olympic_weightlifting:'Levantamento olímpico',strongman:'Strongman'};
  const difficulty = {beginner:'Iniciante',intermediate:'Intermediário',advanced:'Avançado'};
  const force = {push:'Empurrar',pull:'Puxar',static:'Estático',dynamic:'Dinâmico'};
  const mechanic = {compound:'Composto',isolation:'Isolado'};
  const goals = {hypertrophy:'Hipertrofia',strength:'Força',endurance:'Resistência',mobility:'Mobilidade',rehabilitation:'Reabilitação',conditioning:'Condicionamento'};
  const tags = {core_focus:'Foco no core',knee_safe:'Amigável aos joelhos',shoulder_safe:'Amigável aos ombros',lower_back_safe:'Amigável à lombar',no_axial_load:'Sem carga axial',leg_day:'Treino de pernas'};
  const names = {'ab-wheel-rollout':'Abdominal com roda','air-bike':'Air bike','archer-pull-ups':'Barra fixa arqueiro','archer-push-ups':'Flexão arqueiro','arnold-press':'Desenvolvimento Arnold','assisted-dips':'Mergulho assistido na máquina','assisted-pull-ups':'Barra fixa assistida','back-extension':'Extensão lombar','bench-press':'Supino reto','barbell-row':'Remada curvada','romanian-deadlift':'Stiff / terra romeno','lateral-raise':'Elevação lateral','barbell-curl':'Rosca direta','tricep-pushdown':'Tríceps na polia','machine-calf-raise':'Panturrilha na máquina','cable-crunch':'Abdominal na polia','leg-press':'Leg press','incline-db-press':'Supino inclinado com halteres','lat-pulldown':'Puxada alta','leg-curl':'Mesa flexora','dumbbell-shoulder-press':'Desenvolvimento com halteres','cable-fly':'Crossover','hammer-curl':'Rosca martelo','overhead-tricep-extension':'Tríceps francês','seated-calf-raise':'Panturrilha sentado','hanging-leg-raise':'Elevação de pernas','hack-squat':'Hack squat','chest-press-machine':'Supino máquina','seated-cable-row':'Remada sentada','leg-extension':'Cadeira extensora','face-pull':'Face pull','preacher-curl':'Rosca Scott','machine-seated-crunch':'Abdominal máquina','machine-shoulder-press':'Desenvolvimento máquina','crunches':'Abdominal','incline-treadmill-walk':'Caminhada inclinada na esteira','hip-thrust':'Elevação pélvica','bulgarian-split-squat':'Agachamento búlgaro','glute-kickback':'Coice na polia','hip-abduction':'Abdutora','step-up':'Step-up','standing-calf-raise':'Panturrilha em pé','bodyweight-calf-raise':'Panturrilha com peso corporal'};
  const words = {ab:'abdominal',abs:'abdominais',abdominal:'abdominal',wheel:'roda',rollout:'extensão',archer:'arqueiro',pull:'puxada',pulls:'puxadas',push:'empurrada',pushes:'empurradas',ups:'barra fixa',assisted:'assistido',machine:'máquina',back:'costas',extension:'extensão',bench:'banco',press:'supino',barbell:'barra',row:'remada',rows:'remadas',romanian:'romeno',deadlift:'terra',lateral:'lateral',raise:'elevação',raises:'elevações',curl:'rosca',curls:'roscas',tricep:'tríceps',triceps:'tríceps',cable:'polia',calf:'panturrilha',calves:'panturrilhas',seated:'sentado',standing:'em pé',leg:'perna',legs:'pernas',incline:'inclinado',dumbbell:'halteres',shoulder:'ombro',shoulders:'ombros',fly:'crucifixo',hammer:'martelo',overhead:'acima da cabeça',hanging:'suspenso',hack:'hack',chest:'peito',face:'face',preacher:'Scott',crunch:'abdominal',crunches:'abdominais',treadmill:'esteira',walk:'caminhada',walking:'caminhada',hip:'quadril',thrust:'elevação pélvica',split:'dividido',squat:'agachamento',squats:'agachamentos',kickback:'coice',abduction:'abdução',step:'step',up:'subida',weight:'peso',bodyweight:'peso corporal',plate:'anilha',plates:'anilhas',kettlebell:'kettlebell',band:'faixa elástica',bands:'faixas elásticas',rope:'corda',rotation:'rotação',rotations:'rotações',grip:'pegada',neutral:'neutra',wide:'aberta',close:'fechada',narrow:'fechada',single:'unilateral',arm:'braço',arms:'braços',wrist:'punho',neck:'pescoço',good:'bom',morning:'dia',reverse:'invertido',front:'frontal',rear:'posterior',lying:'deitado'};
  const phraseRules = [[/^A full-body conditioning exercise/i,'Exercício de condicionamento para o corpo inteiro'],[/^A (?:core|strength|compound|isolation) exercise/i,'Um exercício'],[/^An isolation movement/i,'Um movimento de isolamento'],[/^A beginner-friendly/i,'Uma variação indicada para iniciantes'],[/^A machine-assisted/i,'Uma variação assistida por máquina'],[/^An overhead press variation/i,'Uma variação de desenvolvimento acima da cabeça'],[/^A wide push-up/i,'Uma flexão com abertura ampla'],[/^A unilateral pull-up/i,'Uma barra fixa unilateral'],[/^Hold a pair of dumbbells/i,'Segure um par de halteres'],[/^Hold /i,'Segure '],[/^Grip /i,'Segure '],[/^Sit on /i,'Sente-se em '],[/^Stand /i,'Fique em pé '],[/^Lie /i,'Deite-se '],[/^Kneel /i,'Ajoelhe-se '],[/^Place your /i,'Posicione seus '],[/^Keep your /i,'Mantenha seu '],[/^Keep /i,'Mantenha '],[/^Lower /i,'Desça '],[/^Raise /i,'Eleve '],[/^Pull /i,'Puxe '],[/^Push /i,'Empurre '],[/^Press /i,'Empurre '],[/^Return /i,'Retorne '],[/^Repeat/i,'Repita'],[/^Avoid /i,'Evite '],[/^Use /i,'Use '],[/^Continue /i,'Continue '],[/^Stop /i,'Pare ']];
  function tokenTranslate(text){return String(text||'').replace(/\b[A-Za-z][A-Za-z'-]*\b/g,t=>words[t.toLowerCase()]||t)}
  function sentence(text){let s=String(text||'').trim();if(!s)return '';for(const [rx,repl] of phraseRules){if(rx.test(s)){s=s.replace(rx,repl);break}}s=s.replace(/\bthe\b/gi,'o').replace(/\band\b/gi,'e').replace(/\bwith\b/gi,'com').replace(/\bwhile\b/gi,'enquanto').replace(/\bfrom\b/gi,'a partir de').replace(/\bto\b/gi,'para').replace(/\binto\b/gi,'para').replace(/\byour\b/gi,'seu').replace(/\byou\b/gi,'você').replace(/\bbody\b/gi,'corpo').replace(/\bchest\b/gi,'peito').replace(/\bback\b/gi,'costas').replace(/\bshoulders\b/gi,'ombros').replace(/\belbows\b/gi,'cotovelos').replace(/\bknees\b/gi,'joelhos').replace(/\bfeet\b/gi,'pés').replace(/\bhands\b/gi,'mãos').replace(/\barms\b/gi,'braços').replace(/\blegs\b/gi,'pernas').replace(/\bweight\b/gi,'carga').replace(/\bslowly\b/gi,'lentamente').replace(/\bcontrolled\b/gi,'controlado').replace(/\bcontrol\b/gi,'controle').replace(/\bposition\b/gi,'posição').replace(/\bstart\b/gi,'inicial').replace(/\bdesired\b/gi,'desejado').replace(/\breps?\b/gi,'repetições').replace(/\bforward\b/gi,'para frente').replace(/\bbackward\b/gi,'para trás').replace(/\bupward\b/gi,'para cima').replace(/\bdownward\b/gi,'para baixo');s=tokenTranslate(s);return s.replace(/\s+/g,' ').trim()}
  function name(ex){if(!ex)return '';if(names[ex.id])return names[ex.id];return tokenTranslate(ex.name_en||ex.id).replace(/\s+/g,' ').trim()}
  function description(ex){return ex?sentence(ex.description_en||''):''}
  function instructions(ex){return ex?(ex.instructions_en||[]).map(sentence):[]}
  function tips(ex){return ex?(ex.tips_en||[]).map(sentence):[]}
  function label(value){const k=String(value||'');return body[k]||equipment[k]||muscles[k]||category[k]||difficulty[k]||force[k]||mechanic[k]||goals[k]||tags[k]||tokenTranslate(k.replace(/_/g,' '))}
  function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
  const aliases={peito:['chest','pectoralis','peitoral'],costas:['back','dorsal','latissimus'],ombro:['shoulder','deltoide'],ombros:['shoulder','deltoide'],braco:['upper_arms','biceps','triceps'],braços:['upper_arms','biceps','triceps'],perna:['upper_legs','quadriceps','hamstrings','glute'],pernas:['upper_legs','quadriceps','hamstrings','glute'],abdomen:['core','abdominais','abdominal'],abdômen:['core','abdominais','abdominal'],panturrilha:['calf','calves','gastrocnemius','soleus'],gluteo:['glute','glutes','hip'],glúteo:['glute','glutes','hip'],halter:['dumbbell'],halteres:['dumbbell'],barra:['barbell','pull_up_bar'],polia:['cable'],maquina:['machine'],máquina:['machine'],supino:['bench','chest press'],remada:['row'],agachamento:['squat'],rosca:['curl'],triceps:['tricep','triceps'],tríceps:['tricep','triceps'],esteira:['treadmill'],abdominal:['crunch','ab wheel','core']};
  function searchTerms(query){const q=normalize(query);if(!q)return [];const terms=[q];Object.keys(aliases).forEach(k=>{if(normalize(k)===q)terms.push(...aliases[k].map(normalize))});return terms}
  function matches(ex,query){const terms=searchTerms(query);if(!terms.length)return true;const hay=normalize([ex.id,ex.name_en,ex.name_de,ex.name_es,name(ex),description(ex),ex.equipment,ex.body_part,...(ex.primary_muscles||[]),...(ex.secondary_muscles||[]),...(ex.tags||[]),...(ex.goals||[]),label(ex.equipment),label(ex.body_part),...(ex.primary_muscles||[]).map(label),...(ex.secondary_muscles||[]).map(label)].join(' '));return terms.some(t=>hay.includes(t))}
  function localized(ex){return {name:name(ex),description:description(ex),instructions:instructions(ex),tips:tips(ex),bodyPart:label(ex.body_part),equipment:ex.is_bodyweight?'Peso corporal':label(ex.equipment),primaryMuscles:(ex.primary_muscles||[]).map(label),secondaryMuscles:(ex.secondary_muscles||[]).map(label),category:label(ex.category),difficulty:label(ex.difficulty),forceType:label(ex.force_type),mechanic:label(ex.mechanic),goals:(ex.goals||[]).map(label),tags:(ex.tags||[]).map(label)}}
  return {body,equipment,muscles,names,name,description,instructions,tips,label,normalize,matches,localized}
})();
