plugins { id 'com.android.application' }

android {
    namespace 'com.matheusboettger.treinotrinca'
    compileSdk 36

    defaultConfig {
        applicationId 'com.matheusboettger.treinotrinca'
        minSdk 23
        targetSdk 36
        versionCode 74
        versionName '2026.10.09.74'
    }

    buildTypes {
        release { minifyEnabled false }
    }
}
